services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appgo.mojotv.cn
    ports:
      - "9528:9528"
    networks:
      - mojo
    depends_on:
      - rdp
      - vnc

  # 提供guac 协议
  guacd:
    container_name: guacd.mojotv.cn
    image: guacamole/guacd:latest
    networks:
      - mojo
    restart: always

  vnc:
    # vnc 图形界面Ubuntu虚拟机容器 password: vncpassword  容器 vnc端口5901
    image: consol/ubuntu-xfce-vnc:latest
    container_name: guacd-vnc.mojotv.cn
    networks:
      - mojo
    depends_on:
      - guacd

  rdp: #rdp 图形界面Ubuntu虚拟机容器  远程桌面支持rdp协议  容器rdp端口 3389
    image: danielguerra/ubuntu-xrdp:latest    # Updated to a more maintained image
    container_name: guacd-rdp.mojotv.cn  #容器名称 aka ( hostname,内网域名)
    environment:
      - USERNAME=root
      - PASSWORD=Docker
    networks:
      - mojo
    depends_on:
      - guacd

networks:
  mojo:
    driver: bridge
